# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="styles",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="styles.style"
            ),
        ),
    ]
